//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.1

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, SimpleObject)]
#[sea_orm(table_name = "allergens")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: Option<String>,
    pub descr: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::food_allergens::Entity")]
    FoodAllergens,
}

impl Related<super::food_allergens::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FoodAllergens.def()
    }
}

impl Related<super::foods::Entity> for Entity {
    fn to() -> RelationDef {
        super::food_allergens::Relation::Foods.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::food_allergens::Relation::Allergens.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::food_allergens::Entity")]
    FoodAllergens,
    #[sea_orm(entity = "super::foods::Entity")]
    Foods,
}
