//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.1

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, SimpleObject)]
#[sea_orm(table_name = "ingredients")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub name: String,
    pub is_vegan: Option<bool>,
    pub is_vegetarian: Option<bool>,
    pub is_gluten_free: Option<bool>,
    pub is_checked: Option<bool>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::food_ingredients::Entity")]
    FoodIngredients,
}

impl Related<super::food_ingredients::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FoodIngredients.def()
    }
}

impl Related<super::foods::Entity> for Entity {
    fn to() -> RelationDef {
        super::food_ingredients::Relation::Foods.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::food_ingredients::Relation::Ingredients.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::food_ingredients::Entity")]
    FoodIngredients,
    #[sea_orm(entity = "super::foods::Entity")]
    Foods,
}
