//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.1

pub mod prelude;

pub mod allergens;
pub mod canteens;
pub mod current_foods;
pub mod food_allergens;
pub mod food_ingredients;
pub mod foods;
pub mod ingredients;
pub mod ratings;
pub mod sea_orm_active_enums;
pub mod users;
