//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.1

pub use super::allergens::Entity as Allergens;
pub use super::canteens::Entity as Canteens;
pub use super::current_foods::Entity as CurrentFoods;
pub use super::food_allergens::Entity as FoodAllergens;
pub use super::food_ingredients::Entity as FoodIngredients;
pub use super::foods::Entity as Foods;
pub use super::ingredients::Entity as Ingredients;
pub use super::ratings::Entity as Ratings;
pub use super::users::Entity as Users;
